/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MapRouteImport } from './routes/map'
import { Route as HbcusRouteImport } from './routes/hbcus'
import { Route as IndexRouteImport } from './routes/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HbcusRoute = HbcusRouteImport.update({
  id: '/hbcus',
  path: '/hbcus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hbcus': typeof HbcusRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hbcus': typeof HbcusRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hbcus': typeof HbcusRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hbcus' | '/map' | '/market' | '/messages' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hbcus' | '/map' | '/market' | '/messages' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/hbcus'
    | '/map'
    | '/market'
    | '/messages'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HbcusRoute: typeof HbcusRoute
  MapRoute: typeof MapRoute
  MarketRoute: typeof MarketRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hbcus': {
      id: '/hbcus'
      path: '/hbcus'
      fullPath: '/hbcus'
      preLoaderRoute: typeof HbcusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HbcusRoute: HbcusRoute,
  MapRoute: MapRoute,
  MarketRoute: MarketRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
