/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentHistoryRouteImport } from './routes/payment-history'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MapRouteImport } from './routes/map'
import { Route as ManagePlanRouteImport } from './routes/manage-plan'
import { Route as HbcusRouteImport } from './routes/hbcus'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentHistoryRoute = PaymentHistoryRouteImport.update({
  id: '/payment-history',
  path: '/payment-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagePlanRoute = ManagePlanRouteImport.update({
  id: '/manage-plan',
  path: '/manage-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const HbcusRoute = HbcusRouteImport.update({
  id: '/hbcus',
  path: '/hbcus',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/hbcus': typeof HbcusRoute
  '/manage-plan': typeof ManagePlanRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/upgrade': typeof UpgradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/hbcus': typeof HbcusRoute
  '/manage-plan': typeof ManagePlanRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/upgrade': typeof UpgradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/hbcus': typeof HbcusRoute
  '/manage-plan': typeof ManagePlanRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/upgrade': typeof UpgradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/hbcus'
    | '/manage-plan'
    | '/map'
    | '/market'
    | '/messages'
    | '/payment-failed'
    | '/payment-history'
    | '/payment-success'
    | '/profile'
    | '/safety'
    | '/upgrade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/hbcus'
    | '/manage-plan'
    | '/map'
    | '/market'
    | '/messages'
    | '/payment-failed'
    | '/payment-history'
    | '/payment-success'
    | '/profile'
    | '/safety'
    | '/upgrade'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/hbcus'
    | '/manage-plan'
    | '/map'
    | '/market'
    | '/messages'
    | '/payment-failed'
    | '/payment-history'
    | '/payment-success'
    | '/profile'
    | '/safety'
    | '/upgrade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  HbcusRoute: typeof HbcusRoute
  ManagePlanRoute: typeof ManagePlanRoute
  MapRoute: typeof MapRoute
  MarketRoute: typeof MarketRoute
  MessagesRoute: typeof MessagesRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentHistoryRoute: typeof PaymentHistoryRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ProfileRoute: typeof ProfileRoute
  SafetyRoute: typeof SafetyRoute
  UpgradeRoute: typeof UpgradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-history': {
      id: '/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof PaymentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-plan': {
      id: '/manage-plan'
      path: '/manage-plan'
      fullPath: '/manage-plan'
      preLoaderRoute: typeof ManagePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hbcus': {
      id: '/hbcus'
      path: '/hbcus'
      fullPath: '/hbcus'
      preLoaderRoute: typeof HbcusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  HbcusRoute: HbcusRoute,
  ManagePlanRoute: ManagePlanRoute,
  MapRoute: MapRoute,
  MarketRoute: MarketRoute,
  MessagesRoute: MessagesRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentHistoryRoute: PaymentHistoryRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ProfileRoute: ProfileRoute,
  SafetyRoute: SafetyRoute,
  UpgradeRoute: UpgradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
